// Token and palette generation (requirements §5.4 and §7).
//
// Reads config/palette.yaml and config/design-tokens.yaml and renders the three
// committed modules under src/generated/. The generator (scripts/generate.ts)
// writes them; test/generated.test.ts renders them again and fails when the
// committed files are stale. Pure apart from reading the two YAML files and the
// Prettier configuration.
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';
import { parse } from 'yaml';

export const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const repoRoot = path.resolve(webRoot, '..', '..');

/** The configuration directory, overridable with CATALEJO_CONFIG_DIR. */
export function configDir(): string {
  const override = process.env.CATALEJO_CONFIG_DIR;
  return override ? path.resolve(override) : path.join(repoRoot, 'config');
}

export const generatedDir = path.join(webRoot, 'src', 'generated');

type Yaml = null | boolean | number | string | Yaml[] | { [key: string]: Yaml };
type YamlMap = Record<string, Yaml>;

function isMap(value: Yaml | undefined): value is YamlMap {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function readYaml(file: string): YamlMap {
  const value = parse(readFileSync(file, 'utf8')) as Yaml;
  if (!isMap(value)) throw new Error(`${file}: expected a mapping at the top level`);
  return value;
}

function section(map: YamlMap, key: string, file: string): YamlMap {
  const value = map[key];
  if (!isMap(value)) throw new Error(`${file}: expected a mapping at "${key}"`);
  return value;
}

function scalar(value: Yaml | undefined, where: string): string {
  if (typeof value === 'string' || typeof value === 'number') return String(value);
  throw new Error(`expected a string or number at ${where}`);
}

const PALETTE_REF = /^palette:([A-Za-z0-9_.]+)$/;

/** Resolves "palette:<section>.<key>" against palette.yaml. */
export function resolvePaletteRef(palette: YamlMap, ref: string): string {
  const match = PALETTE_REF.exec(ref);
  if (!match?.[1]) throw new Error(`not a palette reference: ${ref}`);
  let node: Yaml | undefined = palette;
  for (const part of match[1].split('.')) {
    if (Array.isArray(node)) node = node[Number(part)];
    else if (isMap(node)) node = node[part];
    else node = undefined;
  }
  if (typeof node !== 'string') throw new Error(`unresolved palette reference: ${ref}`);
  return node;
}

function kebab(key: string): string {
  return key.replace(/_/g, '-');
}

const HEADER =
  'Generated by scripts/generate.ts from config/palette.yaml and config/design-tokens.yaml. Do not edit.';

export interface GeneratedFile {
  /** Path relative to packages/web. */
  path: string;
  content: string;
}

interface Loaded {
  palette: YamlMap;
  tokens: YamlMap;
  paletteFile: string;
  tokensFile: string;
}

function load(dir: string): Loaded {
  const paletteFile = path.join(dir, 'palette.yaml');
  const tokensFile = path.join(dir, 'design-tokens.yaml');
  return {
    palette: readYaml(paletteFile),
    tokens: readYaml(tokensFile),
    paletteFile,
    tokensFile,
  };
}

function resolvedColors(loaded: Loaded): Record<string, string> {
  const colors = section(loaded.tokens, 'color', loaded.tokensFile);
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(colors)) {
    const ref = scalar(value, `color.${key}`);
    out[key] = ref.startsWith('palette:') ? resolvePaletteRef(loaded.palette, ref) : ref;
  }
  return out;
}

function paletteModule(loaded: Loaded): string {
  return [
    `// ${HEADER}`,
    '',
    `export const palette = ${JSON.stringify(loaded.palette, null, 2)} as const;`,
    '',
    'export type Palette = typeof palette;',
    '',
  ].join('\n');
}

function tokensModule(loaded: Loaded): string {
  const { tokens, tokensFile } = loaded;
  const value = {
    typography: section(tokens, 'typography', tokensFile),
    color: resolvedColors(loaded),
    spacing: section(tokens, 'spacing', tokensFile),
    layout: section(tokens, 'layout', tokensFile),
    shape: section(tokens, 'shape', tokensFile),
  };
  return [
    `// ${HEADER}`,
    '',
    `export const tokens = ${JSON.stringify(value, null, 2)} as const;`,
    '',
    'export type Tokens = typeof tokens;',
    '',
  ].join('\n');
}

function tokensCss(loaded: Loaded): string {
  const { tokens, tokensFile } = loaded;
  const typography = section(tokens, 'typography', tokensFile);
  const lines: string[] = [
    `/* ${HEADER} */`,
    '',
    '/* Tailwind v4 theme. The default namespaces are reset so that only the',
    '   tokens below exist as utilities: no default colors, fonts, sizes, radii,',
    '   shadows or breakpoints. */',
    '@theme static {',
  ];
  for (const ns of [
    'color',
    'font',
    'font-weight',
    'text',
    'tracking',
    'radius',
    'shadow',
    'inset-shadow',
    'drop-shadow',
    'text-shadow',
    'breakpoint',
  ]) {
    lines.push(`  --${ns}-*: initial;`);
  }
  lines.push('');
  for (const [key, value] of Object.entries(resolvedColors(loaded))) {
    lines.push(`  --color-${kebab(key)}: ${value};`);
  }
  lines.push('');
  for (const [key, value] of Object.entries(section(typography, 'families', tokensFile))) {
    lines.push(`  --font-${kebab(key)}: ${scalar(value, `typography.families.${key}`)};`);
  }
  for (const [key, value] of Object.entries(section(typography, 'weights', tokensFile))) {
    lines.push(`  --font-weight-${kebab(key)}: ${scalar(value, `typography.weights.${key}`)};`);
  }
  for (const [key, value] of Object.entries(section(typography, 'sizes', tokensFile))) {
    lines.push(`  --text-${kebab(key)}: ${scalar(value, `typography.sizes.${key}`)};`);
  }
  for (const [key, value] of Object.entries(section(typography, 'letter_spacing', tokensFile))) {
    lines.push(`  --tracking-${kebab(key)}: ${scalar(value, `typography.letter_spacing.${key}`)};`);
  }
  lines.push('');
  const spacing = section(tokens, 'spacing', tokensFile);
  for (const [key, value] of Object.entries(spacing)) {
    const v = scalar(value, `spacing.${key}`);
    // The 4 px grid is Tailwind's spacing unit, so p-3 is 12 px.
    lines.push(key === 'grid' ? `  --spacing: ${v};` : `  --spacing-${kebab(key)}: ${v};`);
  }
  const layout = section(tokens, 'layout', tokensFile);
  for (const [key, value] of Object.entries(layout)) {
    const v = scalar(value, `layout.${key}`);
    if (key.startsWith('breakpoint_')) {
      lines.push(`  --breakpoint-${kebab(key.slice('breakpoint_'.length))}: ${v};`);
    } else {
      lines.push(`  --spacing-${kebab(key)}: ${v};`);
    }
  }
  lines.push('');
  const shape = section(tokens, 'shape', tokensFile);
  for (const [key, value] of Object.entries(shape)) {
    const v = scalar(value, `shape.${key}`);
    if (key.startsWith('radius_')) {
      lines.push(`  --radius-${kebab(key.slice('radius_'.length))}: ${v};`);
    } else {
      lines.push(`  --shape-${kebab(key)}: ${v};`);
    }
  }
  lines.push('}', '');
  return lines.join('\n');
}

async function format(relativePath: string, source: string): Promise<string> {
  const file = path.join(webRoot, relativePath);
  const options = (await prettier.resolveConfig(file)) ?? {};
  return prettier.format(source, { ...options, filepath: file });
}

/** Renders every generated file from the configuration directory. */
export async function renderGenerated(dir: string = configDir()): Promise<GeneratedFile[]> {
  const loaded = load(dir);
  const raw: GeneratedFile[] = [
    { path: 'src/generated/palette.ts', content: paletteModule(loaded) },
    { path: 'src/generated/tokens.ts', content: tokensModule(loaded) },
    { path: 'src/generated/tokens.css', content: tokensCss(loaded) },
  ];
  return Promise.all(
    raw.map(async (file) => ({ path: file.path, content: await format(file.path, file.content) })),
  );
}

/** The google_fonts_url token, used by the index.html test. */
export function googleFontsUrl(dir: string = configDir()): string {
  const loaded = load(dir);
  const typography = section(loaded.tokens, 'typography', loaded.tokensFile);
  return scalar(typography.google_fonts_url, 'typography.google_fonts_url');
}
