// Token, palette and platform generation (requirements §5.4, §6.1, §7, §8).
//
// Reads config/palette.yaml and config/design-tokens.yaml and renders the three
// committed modules under src/generated/, and reads config/platform.yaml and
// config/export-presets.yaml for a fourth, src/generated/platform.ts, with the
// collection-page thresholds and the export presets. The generator (scripts/generate.ts)
// writes them; test/generated.test.ts renders them again and fails when the
// committed files are stale. Pure apart from reading the YAML files and the
// Prettier configuration.
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';
import { parse } from 'yaml';

export const webRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const repoRoot = path.resolve(webRoot, '..', '..');

/** The configuration directory, overridable with CATALEJO_CONFIG_DIR. */
export function configDir(): string {
  const override = process.env.CATALEJO_CONFIG_DIR;
  return override ? path.resolve(override) : path.join(repoRoot, 'config');
}

export const generatedDir = path.join(webRoot, 'src', 'generated');

type Yaml = null | boolean | number | string | Yaml[] | { [key: string]: Yaml };
type YamlMap = Record<string, Yaml>;

function isMap(value: Yaml | undefined): value is YamlMap {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function readYaml(file: string): YamlMap {
  const value = parse(readFileSync(file, 'utf8')) as Yaml;
  if (!isMap(value)) throw new Error(`${file}: expected a mapping at the top level`);
  return value;
}

function section(map: YamlMap, key: string, file: string): YamlMap {
  const value = map[key];
  if (!isMap(value)) throw new Error(`${file}: expected a mapping at "${key}"`);
  return value;
}

function scalar(value: Yaml | undefined, where: string): string {
  if (typeof value === 'string' || typeof value === 'number') return String(value);
  throw new Error(`expected a string or number at ${where}`);
}

const PALETTE_REF = /^palette:([A-Za-z0-9_.]+)$/;

/** Resolves "palette:<section>.<key>" against palette.yaml. */
export function resolvePaletteRef(palette: YamlMap, ref: string): string {
  const match = PALETTE_REF.exec(ref);
  if (!match?.[1]) throw new Error(`not a palette reference: ${ref}`);
  let node: Yaml | undefined = palette;
  for (const part of match[1].split('.')) {
    if (Array.isArray(node)) node = node[Number(part)];
    else if (isMap(node)) node = node[part];
    else node = undefined;
  }
  if (typeof node !== 'string') throw new Error(`unresolved palette reference: ${ref}`);
  return node;
}

function kebab(key: string): string {
  return key.replace(/_/g, '-');
}

const HEADER =
  'Generated by scripts/generate.ts from config/palette.yaml and config/design-tokens.yaml. Do not edit.';

export interface GeneratedFile {
  /** Path relative to packages/web. */
  path: string;
  content: string;
}

interface Loaded {
  palette: YamlMap;
  tokens: YamlMap;
  paletteFile: string;
  tokensFile: string;
}

function load(dir: string): Loaded {
  const paletteFile = path.join(dir, 'palette.yaml');
  const tokensFile = path.join(dir, 'design-tokens.yaml');
  return {
    palette: readYaml(paletteFile),
    tokens: readYaml(tokensFile),
    paletteFile,
    tokensFile,
  };
}

const PLATFORM_HEADER =
  'Generated by scripts/generate.ts from config/platform.yaml and config/export-presets.yaml. Do not edit.';

function numberAt(map: YamlMap, key: string, where: string): number {
  const value = map[key];
  if (typeof value !== 'number') throw new Error(`expected a number at ${where}.${key}`);
  return value;
}

/**
 * The platform parameters the application reads (requirements §5.4, §6.1):
 * the number of species drawn individually in collection charts and the QC
 * thresholds; and the export presets of requirements §8, key, label key and
 * formats, in file order.
 */
function platformModule(dir: string): string {
  const platformFile = path.join(dir, 'platform.yaml');
  const presetsFile = path.join(dir, 'export-presets.yaml');
  const platform = readYaml(platformFile);
  const thresholds = section(platform, 'thresholds', platformFile);
  const qc = section(platform, 'qc', platformFile);
  const presetsYaml = readYaml(presetsFile);
  const presets = presetsYaml.presets;
  if (!Array.isArray(presets)) throw new Error(`${presetsFile}: presets must be a list`);
  const exportPresets = presets.map((preset, i) => {
    if (!isMap(preset)) throw new Error(`${presetsFile}: presets.${String(i)} must be a mapping`);
    const where = `presets.${String(i)}`;
    const formats = preset.formats;
    if (!Array.isArray(formats)) throw new Error(`${presetsFile}: ${where}.formats must be a list`);
    return {
      key: scalar(preset.key, `${where}.key`),
      labelKey: scalar(preset.label_key, `${where}.label_key`),
      formats: formats.map((format, j) => scalar(format, `${where}.formats.${String(j)}`)),
    };
  });
  const value = {
    chartSpeciesMax: numberAt(thresholds, 'chart_species_max', 'thresholds'),
    qc: {
      completenessMin: numberAt(qc, 'completeness_min', 'qc'),
      contaminationMax: numberAt(qc, 'contamination_max', 'qc'),
    },
  };
  return [
    `// ${PLATFORM_HEADER}`,
    '',
    `export const platformConfig = ${JSON.stringify(value, null, 2)} as const;`,
    '',
    `export const exportPresets = ${JSON.stringify(exportPresets, null, 2)} as const;`,
    '',
    'export type ExportPreset = (typeof exportPresets)[number];',
    '',
  ].join('\n');
}

function resolvedColors(loaded: Loaded): Record<string, string> {
  const colors = section(loaded.tokens, 'color', loaded.tokensFile);
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(colors)) {
    const ref = scalar(value, `color.${key}`);
    out[key] = ref.startsWith('palette:') ? resolvePaletteRef(loaded.palette, ref) : ref;
  }
  return out;
}

/**
 * The marks rules of design-tokens.yaml with their colors resolved: each
 * species outline names the species color it applies to and the outline
 * color, so components never resolve palette references themselves.
 */
function resolvedMarks(loaded: Loaded): { speciesOutlines: Record<string, string | number>[] } {
  const marks = section(loaded.tokens, 'marks', loaded.tokensFile);
  const rules = marks.species_outlines;
  if (!Array.isArray(rules))
    throw new Error(`${loaded.tokensFile}: marks.species_outlines must be a list`);
  return {
    speciesOutlines: rules.map((rule, i) => {
      if (!isMap(rule))
        throw new Error(
          `${loaded.tokensFile}: marks.species_outlines.${String(i)} must be a mapping`,
        );
      const where = `marks.species_outlines.${String(i)}`;
      const index = Number(scalar(rule.species_index, `${where}.species_index`));
      return {
        speciesIndex: index,
        speciesColor: resolvePaletteRef(
          loaded.palette,
          `palette:species.sequence.${String(index)}`,
        ),
        background: scalar(rule.background, `${where}.background`),
        outlineWidth: scalar(rule.outline_width, `${where}.outline_width`),
        outlineColor: resolvePaletteRef(
          loaded.palette,
          scalar(rule.outline_color, `${where}.outline_color`),
        ),
      };
    }),
  };
}

function paletteModule(loaded: Loaded): string {
  return [
    `// ${HEADER}`,
    '',
    `export const palette = ${JSON.stringify(loaded.palette, null, 2)} as const;`,
    '',
    'export type Palette = typeof palette;',
    '',
  ].join('\n');
}

function tokensModule(loaded: Loaded): string {
  const { tokens, tokensFile } = loaded;
  const value = {
    typography: section(tokens, 'typography', tokensFile),
    color: resolvedColors(loaded),
    spacing: section(tokens, 'spacing', tokensFile),
    layout: section(tokens, 'layout', tokensFile),
    shape: section(tokens, 'shape', tokensFile),
    marks: resolvedMarks(loaded),
  };
  return [
    `// ${HEADER}`,
    '',
    `export const tokens = ${JSON.stringify(value, null, 2)} as const;`,
    '',
    'export type Tokens = typeof tokens;',
    '',
  ].join('\n');
}

function tokensCss(loaded: Loaded): string {
  const { tokens, tokensFile } = loaded;
  const typography = section(tokens, 'typography', tokensFile);
  const lines: string[] = [
    `/* ${HEADER} */`,
    '',
    '/* Tailwind v4 theme. The default namespaces are reset so that only the',
    '   tokens below exist as utilities: no default colors, fonts, sizes, line',
    '   heights, radii, shadows or breakpoints. */',
    '@theme static {',
  ];
  for (const ns of [
    'color',
    'font',
    'font-weight',
    'text',
    'leading',
    'tracking',
    'radius',
    'shadow',
    'inset-shadow',
    'drop-shadow',
    'text-shadow',
    'breakpoint',
  ]) {
    lines.push(`  --${ns}-*: initial;`);
  }
  lines.push('');
  for (const [key, value] of Object.entries(resolvedColors(loaded))) {
    lines.push(`  --color-${kebab(key)}: ${value};`);
  }
  lines.push('');
  for (const [key, value] of Object.entries(section(typography, 'families', tokensFile))) {
    lines.push(`  --font-${kebab(key)}: ${scalar(value, `typography.families.${key}`)};`);
  }
  for (const [key, value] of Object.entries(section(typography, 'weights', tokensFile))) {
    lines.push(`  --font-weight-${kebab(key)}: ${scalar(value, `typography.weights.${key}`)};`);
  }
  for (const [key, value] of Object.entries(section(typography, 'sizes', tokensFile))) {
    lines.push(`  --text-${kebab(key)}: ${scalar(value, `typography.sizes.${key}`)};`);
  }
  for (const [key, value] of Object.entries(section(typography, 'line_heights', tokensFile))) {
    lines.push(`  --leading-${kebab(key)}: ${scalar(value, `typography.line_heights.${key}`)};`);
  }
  for (const [key, value] of Object.entries(section(typography, 'letter_spacing', tokensFile))) {
    lines.push(`  --tracking-${kebab(key)}: ${scalar(value, `typography.letter_spacing.${key}`)};`);
  }
  lines.push('');
  const spacing = section(tokens, 'spacing', tokensFile);
  for (const [key, value] of Object.entries(spacing)) {
    const v = scalar(value, `spacing.${key}`);
    // The 4 px grid is Tailwind's spacing unit, so p-3 is 12 px.
    lines.push(key === 'grid' ? `  --spacing: ${v};` : `  --spacing-${kebab(key)}: ${v};`);
  }
  const layout = section(tokens, 'layout', tokensFile);
  for (const [key, value] of Object.entries(layout)) {
    const v = scalar(value, `layout.${key}`);
    if (key.startsWith('breakpoint_')) {
      lines.push(`  --breakpoint-${kebab(key.slice('breakpoint_'.length))}: ${v};`);
    } else {
      lines.push(`  --spacing-${kebab(key)}: ${v};`);
    }
  }
  lines.push('');
  const shape = section(tokens, 'shape', tokensFile);
  for (const [key, value] of Object.entries(shape)) {
    const v = scalar(value, `shape.${key}`);
    if (key.startsWith('radius_')) {
      lines.push(`  --radius-${kebab(key.slice('radius_'.length))}: ${v};`);
    } else {
      lines.push(`  --shape-${kebab(key)}: ${v};`);
    }
  }
  lines.push('}', '');
  return lines.join('\n');
}

async function format(relativePath: string, source: string): Promise<string> {
  const file = path.join(webRoot, relativePath);
  const options = (await prettier.resolveConfig(file)) ?? {};
  return prettier.format(source, { ...options, filepath: file });
}

/** Renders every generated file from the configuration directory. */
export async function renderGenerated(dir: string = configDir()): Promise<GeneratedFile[]> {
  const loaded = load(dir);
  const raw: GeneratedFile[] = [
    { path: 'src/generated/palette.ts', content: paletteModule(loaded) },
    { path: 'src/generated/tokens.ts', content: tokensModule(loaded) },
    { path: 'src/generated/tokens.css', content: tokensCss(loaded) },
    { path: 'src/generated/platform.ts', content: platformModule(dir) },
  ];
  return Promise.all(
    raw.map(async (file) => ({ path: file.path, content: await format(file.path, file.content) })),
  );
}

/** The google_fonts_url token, used by the index.html test. */
export function googleFontsUrl(dir: string = configDir()): string {
  const loaded = load(dir);
  const typography = section(loaded.tokens, 'typography', loaded.tokensFile);
  return scalar(typography.google_fonts_url, 'typography.google_fonts_url');
}
